Navigation via ChromeableStage
WycliffeAssociates/8woc2018-jvm pull request #489
Opened 2019-08-28 03:08 UTC by KJoslyn

Requires common [#124](https://github.com/WycliffeAssociates/otter-common/pull/124).

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489)

2019-08-28 19:29 UTC, jsarabia requested changes
> Reviewed 10 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489)* status: 10 of 28 files reviewed, 18 unresolved discussions (waiting on @aunger, @KJoslyn, and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/cardgrid/viewmodel/CardGridViewModel.kt, line 21 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnObsul5tH8_40mycvZ:-LnObsum2mWkFXJ4mU4o:b-jg32ow) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/cardgrid/viewmodel/CardGridViewModel.kt#L21)):*
> ```Kotlin
> 
> class CardGridViewModel : ViewModel() {
>     private val navigator: ChromeableStage by inject()
> ```

this doesn't belong in the viewmodel
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/ChromeableStage.kt, line 21 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOIaRuBSyqIS7_kc4A:-LnOIaRv-ykAL0D8SqHj:b-ycooh3) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/ChromeableStage.kt#L21)):*
> ```Kotlin
>     override val tabGroupBuilder = TabGroupBuilder()
> 
>     override val root = ChromeableTabPane(listMenu(), 0.66).apply {
> ```

can the .66 be a variable with a name?
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/ChromeableStage.kt, line 35 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOHzPjAXFxcAR41EJF:-LnOHzPjAXFxcAR41EJG:b4614ye) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/ChromeableStage.kt#L35)):*
> ```Kotlin
>     }
> 
>     private fun listMenu() = ListMenu().apply {
> ```

I feel like "ChromeableStage" implies it is a stage that can be "chromed." As in, you can place a "Chrome" within it, but here you're making the chrome part of this.

Understanding that really we have no real functionality in any of this, It's fine, it's all placeholder anyway, but "chrome" should be a constructor parameter here.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/RecordResourceTabGroup.kt, line 25 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOIuIvAcQzLFnvokI0:-LnOIuIvAcQzLFnvokI1:b-7h9nfu) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/RecordResourceTabGroup.kt#L25)):*
> ```Kotlin
>     override fun activate() {
>         tabs.forEach { tab ->
>             if (tab.isActive()) {
> ```

what?
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/RecordScriptureTabGroup.kt, line 11 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOfNaa1LcUX6prOhIk:-LnOfNaa1LcUX6prOhIl:bbgy1di) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/RecordScriptureTabGroup.kt#L11)):*
> ```Kotlin
>         tabPane.tabs.add(
>             Tab().apply {
>                 add(RecordScriptureFragment().root)
> ```

you can't just add the fragment?
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectChapterTabGroup.kt, line 9 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOPmqB4I9bv7EIcD5H:-LnOPmqB4I9bv7EIcD5I:bm80gf2) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectChapterTabGroup.kt#L9)):*
> ```Kotlin
> import tornadofx.*
> 
> class SelectChapterTabGroup : TabGroup() {
> ```

The word Select is unnecessary 
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectChapterTabGroup.kt, line 14 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOPsW17BCtRU6ileQd:-LnOPsW17BCtRU6ileQe:b-ox9oxu) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectChapterTabGroup.kt#L14)):*
> ```Kotlin
>     override fun activate() {
>         workbookViewModel.activeChapterProperty.set(null)
>         val currentActiveResourceInfo = workbookViewModel.activeResourceInfoProperty.value
> ```

current and active sound synonymous. Can you have an active resourceinfo that isn't current?
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectChapterTabGroup.kt, line 26 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOP4bwC8wqBpp6kiFR:-LnOP4bx8YxghWgE1S-H:b-l08mmp) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectChapterTabGroup.kt#L26)):*
> ```Kotlin
>     }
> 
>     private fun getTargetBookResourceInfo() =
> ```

don't use single expression syntax here
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectProjectTabGroup.kt, line 7 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOQD990-8WMsVdM7sZ:-LnOQD990-8WMsVdM7s_:b-q00y9t) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectProjectTabGroup.kt#L7)):*
> ```Kotlin
> import tornadofx.*
> 
> class SelectProjectTabGroup : TabGroup() {
> ```

Select is unnecessary
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectRecordableTabGroup.kt, line 8 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOPVp02y79o-t8gY9K:-LnOPVp02y79o-t8gY9L:b8kmyt8) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectRecordableTabGroup.kt#L8)):*
> ```Kotlin
> import tornadofx.*
> 
> class SelectRecordableTabGroup : TabGroup() {
> ```

This name doesn't make sense.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectRecordableTabGroup.kt, line 18 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOQJAZDF9F18bayD3R:-LnOQJAZDF9F18bayD3S:buxsbpl) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectRecordableTabGroup.kt#L18)):*
> ```Kotlin
>     }
> 
>     private fun createChooseChunkTab() {
> ```

createChunkTab
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectRecordableTabGroup.kt, line 26 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOQKk3Cy9PVnYXBWk_:-LnOQKk41_LmH8gwu0AT:bj68q06) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectRecordableTabGroup.kt#L26)):*
> ```Kotlin
>     }
> 
>     private fun createChooseResourceTab() {
> ```

createResourceTab
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/TabGroup.kt, line 10 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOQRsCDF-zJVBPMctN:-LnOQRsCDF-zJVBPMctO:b-bhrwiy) ([raw file](https://github.com/wycliffeassociates/ot [...]

2019-08-28 20:30 UTC, jsarabia reviewed
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489)* status: 10 of 28 files reviewed, 17 unresolved discussions (waiting on @aunger and @KJoslyn)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/TabGroupBuilder.kt, line 5 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOSR4qAGzUJ7lJ0fCK:-LnOuzuOAEuVOIIslll2:b-jcs983) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/TabGroupBuilder.kt#L5)):*
<details><summary><i>Previously, sarabiaj (Joe) wrote…</i></summary><blockquote>

what value does this provide?
</blockquote></details>

reading the interface in common made sense, sorry about that


<!-- Sent from Reviewable.io -->

2019-08-28 23:18 UTC, aunger requested changes
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489)* status: 10 of 28 files reviewed, 19 unresolved discussions (waiting on @aunger, @KJoslyn, and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/ChromeableStage.kt, line 18 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnPKkFd9d7BIGWHtYKy:-LnPKkFd9d7BIGWHtYKz:by39rlx) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/ChromeableStage.kt#L18)):*
> ```Kotlin
>     override val tabGroupMap: MutableMap<TabGroupType, ITabGroup> = mutableMapOf()
>     override val navBackStack = Stack<ITabGroup>()
>     override var currentGroup: ITabGroup? = null
> ```

Nit: set off the var with blank lines and/or reorder it above or below the vals.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectChapterTabGroup.kt, line 39 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnPMse5EwKStdb0T40N:-LnPMse5EwKStdb0T40O:b40uu5o) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectChapterTabGroup.kt#L39)):*
> ```Kotlin
>             .startWith(getTargetBookResourceInfo())
>             .map { info ->
>                 tabMap.putIfAbsent(info.slug, ChapterSelectTab(info))
> ```

Don't use `map` to cause side-effects.  Use something like `forEach`.
Edit:
Consider removing the extension method and do this:
```kotlin
        (sequenceOf(getTargetBookResourceInfo()) + workbookViewModel.workbook.source.subtreeResources)
            .forEach { info ->
                tabMap.putIfAbsent(info.slug, ChapterSelectTab(info))
            }
```
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/utils/TornadoFXUtils.kt, line 60 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOWNHQ36ZGc9MN8Y8P:-LnPUoYf1uQZO1J2j8-h:b2ngthx) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/utils/TornadoFXUtils.kt#L60)):*
<details><summary><i>Previously, sarabiaj (Joe) wrote…</i></summary><blockquote>

prepend
also, given that List is not a tornadofx class, I don't know if I feel like it belongs in TornadoFXUtils
</blockquote></details>

+1 


<!-- Sent from Reviewable.io -->

2019-08-29 17:59 UTC, KJoslyn reviewed
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489)* status: 6 of 28 files reviewed, 18 unresolved discussions (waiting on @aunger and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/cardgrid/viewmodel/CardGridViewModel.kt, line 21 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnObsul5tH8_40mycvZ:-LnTV5ml-NiiMhegRM5h:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/cardgrid/viewmodel/CardGridViewModel.kt#L21)):*
<details><summary><i>Previously, sarabiaj (Joe) wrote…</i></summary><blockquote>

this doesn't belong in the viewmodel
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/ChromeableStage.kt, line 18 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnPKkFd9d7BIGWHtYKy:-LnTV8gl8i_EDF1IrRYf:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/ChromeableStage.kt#L18)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Nit: set off the var with blank lines and/or reorder it above or below the vals.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/ChromeableStage.kt, line 21 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOIaRuBSyqIS7_kc4A:-LnTVC4_4FImIH0ZK-re:b-fdxptf) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/ChromeableStage.kt#L21)):*
<details><summary><i>Previously, sarabiaj (Joe) wrote…</i></summary><blockquote>

can the .66 be a variable with a name?
</blockquote></details>

Sure, I made a val for it, now in MainScreenView.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/ChromeableStage.kt, line 35 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOHzPjAXFxcAR41EJF:-LnOryE8-nDLYsr3Sal7:b-2l0fy4) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/ChromeableStage.kt#L35)):*
<details><summary><i>Previously, sarabiaj (Joe) wrote…</i></summary><blockquote>

I feel like "ChromeableStage" implies it is a stage that can be "chromed." As in, you can place a "Chrome" within it, but here you're making the chrome part of this.

Understanding that really we have no real functionality in any of this, It's fine, it's all placeholder anyway, but "chrome" should be a constructor parameter here.
</blockquote></details>

I refactored ChromeableStage to accept a few parameters now- previously I didn't know how to do this!

https://github.com/edvin/tornadofx-guide/blob/master/part1/3.%20Components.md#passing-parameters-to-views
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/RecordResourceTabGroup.kt, line 25 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOIuIvAcQzLFnvokI0:-LnOtVB785oblREpOiOH:b-6r600k) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/RecordResourceTabGroup.kt#L25)):*
<details><summary><i>Previously, sarabiaj (Joe) wrote…</i></summary><blockquote>

what?
</blockquote></details>

I renamed this function to hasRecordable(). Also renamed "tab ->" to "recordableTab ->" so that it is obvious that these are RecordableTabs.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/RecordScriptureTabGroup.kt, line 11 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOfNaa1LcUX6prOhIk:-LnOuraX10eufIHJYAoX:b-8zkugd) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/RecordScriptureTabGroup.kt#L11)):*
<details><summary><i>Previously, sarabiaj (Joe) wrote…</i></summary><blockquote>

you can't just add the fragment?
</blockquote></details>

The Fragment itself isn't a node, so not this way. But, there is another way...
```
tabPane.apply {
    tab<RecordScriptureFragment> {}
}

It turns out that this way of doing it still instantiates a new Fragment each time, likely since Fragments are not ScopedInstances/Singletons.
```

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectProjectTabGroup.kt, line 7 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOQD990-8WMsVdM7sZ:-LnTWTsF-zbJEPAqWUIi:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectProjectTabGroup.kt#L7)):*
<details><summary><i>Previously, sarabiaj (Joe) wrote…</i></summary><blockquote>

Select is unnecessary
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectRecordableTabGroup.kt, line 8 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOPVp02y79o-t8gY9K:-LnTWVEGCHOPQNWuozuw:b27ry0z) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectRecordableTabGroup.kt#L8)):*
<details><summary><i>Previously, sarabiaj (Joe) wrote…</i></summary><blockquote>

This name doesn't make sense.
</blockquote></details>

After our brief talk about this yesterday, I kept it the same except removed "Select" as I did for the other TabGroups. There may still be a better name.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectRecordableTabGroup.kt, line 18 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOQJAZDF9F18bayD3R:-LnTWgpnAsWrY0JzlCWM:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectRecordableTabGroup.kt#L18)):*
<details><summary><i>Previously, sarabiaj (Joe) wrote…</i></summary><blockquote>

createChunkTab
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectRecordableTabGroup.kt, line 26 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOQKk3Cy9PVnYXBWk_:-LnTWhKZ9aRRDihayQS8:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectRecordableTabGroup.kt#L26)):*
<details><summary><i>Previously, sarabiaj (Joe) wrote…</i></summary><blockquote>

createResourceTab
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/TabGroup.kt, line 10 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnOQRsCDF-zJVBPMctN:-LnTWiRW47buNNVVTwJB:b-ajuo3t) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/TabGroup.kt#L10)):*
<details><summary><i>Previously, sarabiaj (Joe) wrote…</i></summary><blockquote>

this doesn't belong here
</blockquote></details>

I moved this into the TabGroup subclasses that actually use `workbookViewModel`.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ [...]

2019-08-29 19:08 UTC, aunger approved these changes
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489)* status: 6 of 28 files reviewed, 17 unresolved discussions (waiting on @aunger and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectChapterTabGroup.kt, line 39 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489#-LnPMse5EwKStdb0T40N:-LnTkU_jCGygwPACnK2D:b-ykqvfj) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b1ddb2e2d04dbbd545027a57d74666db2ff6673c/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/chromeablestage/tabgroups/SelectChapterTabGroup.kt#L39)):*
<details><summary><i>Previously, KJoslyn wrote…</i></summary><blockquote>

I suppose I actually could have used `forEach` instead of `map`. I would say if I do that, it looks cleaner. But your way doesn't require the extension method so should I still prefer that?
</blockquote></details>

I'm pretty flexible on everything except using `.map` to produce side-effects.  (`map` certainly _works_, but the reader's expectation is that `map` just transforms a sequence, while `forEach` performs actions outside of the sequence (side-effects)).

Might even be simplest to run `putIfAbsent` on the target, and then iterate applying `putIfAbsent` on the sources.  It'd be a small amount of redundancy, but would remove the whole question of how to concatenate these things.

It looks fine as-is to me, though.


<!-- Sent from Reviewable.io -->

2019-09-04 07:22 UTC, aunger approved these changes
> Reviewed 13 of 28 files at r1, 18 of 19 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489)* status: all files reviewed, 17 unresolved discussions (waiting on @sarabiaj)



<!-- Sent from Reviewable.io -->

2019-09-04 21:56 UTC, aunger approved these changes

2019-09-04 21:58 UTC, aunger approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489)* status: all files reviewed, 17 unresolved discussions (waiting on @sarabiaj)



<!-- Sent from Reviewable.io -->

2019-09-09 17:36 UTC, jsarabia approved these changes
> Reviewed 7 of 28 files at r1, 18 of 19 files at r2, 9 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-09-09 17:36 UTC, jsarabia approved these changes
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/489)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-09-09 17:41 UTC, merged